CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    nickname VARCHAR(64) NOT NULL,
    phone VARCHAR(32) NULL,
    email VARCHAR(128) NULL,
    role_code VARCHAR(32) NOT NULL DEFAULT 'USER',
    status TINYINT(1) NOT NULL DEFAULT 1,
    last_login_at DATETIME NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    UNIQUE KEY uk_sys_user_username (username),
    KEY idx_sys_user_status (status)
);

CREATE TABLE IF NOT EXISTS workspace (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    owner_user_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(500) NULL,
    status TINYINT(1) NOT NULL DEFAULT 1,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    UNIQUE KEY uk_workspace_owner_name (owner_user_id, name, deleted),
    KEY idx_workspace_owner_user_id (owner_user_id)
);

CREATE TABLE IF NOT EXISTS flow_graph (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    workspace_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(500) NULL,
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL',
    graph_status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    graph_version BIGINT NOT NULL DEFAULT 1,
    total_time INT NOT NULL DEFAULT 0,
    total_precision DECIMAL(10,4) NOT NULL DEFAULT 0.0000,
    total_cost INT NOT NULL DEFAULT 0,
    last_import_at DATETIME NULL,
    last_export_at DATETIME NULL,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    UNIQUE KEY uk_flow_graph_workspace_name (workspace_id, name, deleted),
    KEY idx_flow_graph_workspace_id (workspace_id),
    KEY idx_flow_graph_created_by (created_by),
    KEY idx_flow_graph_graph_version (graph_version),
    KEY idx_flow_graph_workspace_status (workspace_id, graph_status)
);

CREATE TABLE IF NOT EXISTS equipment (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    graph_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(500) NULL,
    color VARCHAR(32) NULL,
    image_path VARCHAR(255) NULL,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    UNIQUE KEY uk_equipment_graph_name (graph_id, name, deleted),
    KEY idx_equipment_graph_id (graph_id)
);

CREATE TABLE IF NOT EXISTS process_node (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    graph_id BIGINT NOT NULL,
    node_code VARCHAR(64) NOT NULL,
    node_name VARCHAR(128) NULL,
    node_description VARCHAR(255) NULL,
    equipment_id BIGINT NULL,
    time_cost INT NOT NULL DEFAULT 0,
    precision_value DECIMAL(10,4) NOT NULL DEFAULT 0.0000,
    cost_value INT NOT NULL DEFAULT 0,
    sort_no INT NOT NULL DEFAULT 0,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    UNIQUE KEY uk_process_node_graph_code (graph_id, node_code, deleted),
    KEY idx_process_node_graph_id (graph_id),
    KEY idx_process_node_equipment_id (equipment_id)
);

CREATE TABLE IF NOT EXISTS process_path (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    graph_id BIGINT NOT NULL,
    start_node_id BIGINT NOT NULL,
    end_node_id BIGINT NOT NULL,
    relation_type VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
    remark VARCHAR(255) NULL,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    UNIQUE KEY uk_process_path_graph_start_end (graph_id, start_node_id, end_node_id, deleted),
    KEY idx_process_path_graph_id (graph_id),
    KEY idx_process_path_start_node_id (start_node_id),
    KEY idx_process_path_end_node_id (end_node_id)
);

CREATE TABLE IF NOT EXISTS constraint_condition (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    graph_id BIGINT NOT NULL,
    condition_code VARCHAR(64) NOT NULL,
    condition_type VARCHAR(32) NOT NULL,
    condition_description VARCHAR(255) NULL,
    node_id_1 BIGINT NOT NULL,
    node_id_2 BIGINT NOT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    UNIQUE KEY uk_constraint_condition_graph_code (graph_id, condition_code, deleted),
    UNIQUE KEY uk_constraint_condition_graph_pair_type (graph_id, node_id_1, node_id_2, condition_type, deleted),
    KEY idx_constraint_condition_graph_id (graph_id),
    KEY idx_constraint_condition_node1 (node_id_1),
    KEY idx_constraint_condition_node2 (node_id_2)
);

CREATE TABLE IF NOT EXISTS optimize_task (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    task_no VARCHAR(64) NOT NULL,
    workspace_id BIGINT NOT NULL,
    graph_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    algorithm_type TINYINT NOT NULL,
    algorithm_mode TINYINT NOT NULL,
    time_weight INT NOT NULL DEFAULT 1,
    precision_weight INT NOT NULL DEFAULT 1,
    cost_weight INT NOT NULL DEFAULT 1,
    task_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    retry_count INT NOT NULL DEFAULT 0,
    max_retry_count INT NOT NULL DEFAULT 3,
    queue_time DATETIME NOT NULL,
    started_at DATETIME NULL,
    finished_at DATETIME NULL,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(1000) NULL,
    result_id BIGINT NULL,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    UNIQUE KEY uk_optimize_task_task_no (task_no),
    KEY idx_optimize_task_workspace_id (workspace_id),
    KEY idx_optimize_task_graph_id (graph_id),
    KEY idx_optimize_task_user_id (user_id),
    KEY idx_optimize_task_status_queue_time (task_status, queue_time)
);

CREATE TABLE IF NOT EXISTS optimize_result (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    task_id BIGINT NOT NULL,
    workspace_id BIGINT NOT NULL,
    source_graph_id BIGINT NOT NULL,
    result_name VARCHAR(128) NULL,
    result_graph_json LONGTEXT NOT NULL,
    diff_json LONGTEXT NOT NULL,
    map_code LONGTEXT NULL,
    total_time_before INT NOT NULL DEFAULT 0,
    total_precision_before DECIMAL(10,4) NOT NULL DEFAULT 0.0000,
    total_cost_before INT NOT NULL DEFAULT 0,
    total_time_after INT NOT NULL DEFAULT 0,
    total_precision_after DECIMAL(10,4) NOT NULL DEFAULT 0.0000,
    total_cost_after INT NOT NULL DEFAULT 0,
    score_ratio DECIMAL(12,6) NULL,
    yaml_export_path VARCHAR(255) NULL,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    UNIQUE KEY uk_optimize_result_task_id (task_id),
    KEY idx_optimize_result_workspace_id (workspace_id),
    KEY idx_optimize_result_source_graph_id (source_graph_id),
    KEY idx_optimize_result_created_at (created_at)
);

CREATE TABLE IF NOT EXISTS operation_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NULL,
    workspace_id BIGINT NULL,
    graph_id BIGINT NULL,
    task_id BIGINT NULL,
    operation_type VARCHAR(64) NOT NULL,
    object_type VARCHAR(64) NOT NULL,
    object_id BIGINT NULL,
    request_method VARCHAR(16) NULL,
    request_uri VARCHAR(255) NULL,
    request_params LONGTEXT NULL,
    response_code INT NULL,
    success_flag TINYINT(1) NOT NULL DEFAULT 1,
    error_message VARCHAR(1000) NULL,
    cost_time_ms INT NULL,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    KEY idx_operation_log_user_id (user_id),
    KEY idx_operation_log_workspace_id (workspace_id),
    KEY idx_operation_log_graph_id (graph_id),
    KEY idx_operation_log_task_id (task_id),
    KEY idx_operation_log_created_at (created_at),
    KEY idx_operation_log_operation_type (operation_type)
);
